# Visit https://docs.keel.so/envvars for more information about environment variables
environment:

# Visit https://docs.keel.so/secrets for more information about secrets
secrets:
 - name: TAKEALOT_API_KEY